# Generated by Django 2.2.6 on 2019-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Tipo_Identificacion', models.CharField(max_length=10)),
                ('C_I', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Apellido_Paterno', models.CharField(max_length=35)),
                ('Apellido_Materno', models.CharField(max_length=35)),
                ('Primer_Nombre', models.CharField(max_length=35)),
                ('Segundo_Nombre', models.CharField(max_length=35)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Edad', models.CharField(max_length=10)),
                ('Sexo', models.CharField(max_length=10)),
                ('Tipo_Sangre', models.CharField(max_length=10)),
                ('Lugar_Nacimiento', models.CharField(max_length=10)),
                ('Lugar_Residencia', models.CharField(max_length=10)),
                ('Instruccion', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Tipo_Licencia', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=10)),
            ],
        ),
    ]
