# Generated by Django 2.2.6 on 2019-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Instruccion',
            new_name='Dirección',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Telefono',
            new_name='Instrucción',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Tipo_Identificacion',
            new_name='Teléfono',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Tipo_Identificación',
            field=models.CharField(choices=[('P', 'Pasaporte'), ('C', 'Cedula de Identidad')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
    ]
