# Generated by Django 2.2.6 on 2019-10-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_curso_matriula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matriula',
            new_name='Matricula',
        ),
    ]
